#!/bin/sh
#
# Run bin/dot_update for first-installation
# this is an internal script file (helper)
# Run all dotfiles installers.
# 
set -e

# 
#export DOTFILES=$(dirname "$0")/..
#cd $DOTFILES
export PATH=$PATH:$DOTFILES/bin

# find the installers and run them iteratively
LIST=$(git ls-tree --name-only -r HEAD | grep install.sh)

for installer in $LIST; do
  echo "› ${installer}..."
  sh "$installer"
done
   
